version: 2.1
executors:
  my-executor:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    working_directory: /opt/drupal
defaults: &defaults
  docker:
    - image: quay.io/pantheon-public/terminus-plugin-test:1.x
  working_directory: ~/work/terminus_plugin
  environment:
    BASH_ENV: ~/.bashrc
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb
jobs: # conditional steps may also be defined in `commands:`
  job_with_optional_custom_checkout:
    parameters:
      custom_checkout:
        type: string
        default: ""
    machine: true
    steps:
      - when:
          condition: <<parameters.custom_checkout>>
          steps:
            - run: echo "my custom checkout"
      - unless:
          condition: <<parameters.custom_checkout>>
          steps:
            - checkout
  job_to_deploy_on_pantheon:
    environment:
      TZ: "/usr/share/zoneinfo/America/New_York"
      TERMINUS_SITE:  "reacts"
      TERMINUS_TOKEN: "R81d0KN9SsarKcQKJlSyp8ufixvHBb3s8eo13XUuFZorb"
      GITHUB_TOKEN:   "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"
      GIT_EMAIL:      "19geeta65@gmail.com"
      ADMIN_USERNAME: admin
      TERM: dumb
      NOTIFY: 'scripts/github/add-commit-comment {project} {sha} "Created multidev environment [{site}#{env}]({dashboard-url})." {site-url}'
    machine: true
    steps:
      - checkout
      - run:
          name: Set up environment
          command: /build-tools-ci/scripts/set-environment
      - run:
          name: Dependencies
          command: composer install
      - run:
          name: Lint
          command: composer lint
      - run:
          name: Unit
          command: composer unit
      - run:
          name: Functional
          command: composer functional
      - run:
          name: Style
          command: composer cs
workflows:
  build-test-deploy:
    jobs:
      - job_with_optional_custom_checkout:
          custom_checkout: "any non-empty string is truthy"
      - job_with_optional_custom_checkout
      - job_to_deploy_on_pantheon